apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

metadata:
  name: security-component
  annotations:
    config.kubernetes.io/local-config: "true"

resources:
- network-policy.yaml
- pod-security-policy.yaml

patches:
- target:
    kind: Deployment
  patch: |-
    spec:
      template:
        spec:
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            fsGroup: 1000
          containers:
          - name: "*"
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                - ALL

commonLabels:
  security.kubernetes.io/enforced: "true"

commonAnnotations:
  security.kubernetes.io/policy-version: "v1.0.0"
